version: '3.4'

services:
  lpms.api:
    image: ${DOCKER_REGISTRY-}lpmsapi
    container_name: lpms.api
    build:
      context: .
      dockerfile: LPMS.API/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"

  lpms.database:
    image: postgres:latest
    container_name: lpms.database
    environment:
        - POSTGRES_DB=LPMS
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
    volumes:
        - ./.containers/lpms-db:/var/lib/postgresql/data
    ports:
        - 1234:1234