# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  lpms.api:
    build:
      context: "C:\\Nikola\\Active Projects\\LPMS\\LPMS.API"
      dockerfile: "LPMS.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/LPMS.API.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "lpmsapi:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "C:\\Nikola\\Active Projects\\LPMS\\LPMS.API\\LPMS.API:/app:rw"
    - "C:\\Nikola\\Active Projects\\LPMS\\LPMS.API:/src:rw"
    - "C:\\Users\\Nikola\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Nikola\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.7\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Nikola\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_1_11_22_45_00:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
